
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-22T06:12:18-1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b2ccab2dab3acad7531cd499dd77785f723f88c",
 "version": "3.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
