language: minimal

sudo: false

env:
  global:
    - secure: "i/Uj39kBUz9zrzUY86OUkAe8zrKlKijuVzADqdlV8YCgiCuuP/d7ZUlS13SSXRXeiSlDAUSta4wqFkmLL/EfdIiLRRAooM12D1xMEozL/suoi3wS8B2WTZ0J4On5u5na6sCtI/9YqjlZ3RzKfPl3j11ye0VldLR6Rdf/VQpW80+QpqCeiEmBzbUeRHWOiOTT7Joo4dGwgnBlUtYWmTC4nAydrMuko0cznueKf7x2dGBpcBoFF9ylZP08V1vH2Y7OC6Nd/oEKS8MoKstXUNk0QamVEXeZejjska/7odyCt9uWOCdCN594H6G7ECbQz5UvlUiOWL/jb9UsIhosvKMLGt5lg50LAMZphMq/FARU/oA+gIf3m5EvOODFNvDK7/3OJXrVkD07fkFDhe99mo4/hgiadkQVx0RIXIRcG2vO9LbyOBux2ASjYR7clv0q7Rj6zckt3L/knU8tXOQbW2VSx2czQFFNIC1EFP6h5ydK0s/bRMWO23xOToxdRlyFYn5HVwYpxPGFvFywjyWm4lkCBvb1s4UuriWe4ikVTyNdukchpwLaP9Uz02I5pVPkKdkiv3SGS+jjCoQdGSnOmk13ruqszUxgfb5BSkD0ACrGos4O0NG/8TDXuxf8nKS1bwATIIwAp0cCYgIxolODFU79YS6hSOHr2RJxdlwl9bQVykk="

matrix:
  fast_finish: true
  include:
  - name: py36-np111
    env: TEST_TARGET=default NUMPY=1.11 PY=3.6
  - name: py36-np116
    env: TEST_TARGET=default NUMPY=1.16 PY=3.6
  - name: py37-np111
    env: TEST_TARGET=default NUMPY=1.11 PY=3.7
  - name: py37-np116
    env: TEST_TARGET=default NUMPY=1.16 PY=3.7
  - name: deploy
    env: NUMPY=1.16 PY=3.7

before_install:
  - |
    wget http://bit.ly/miniconda -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update conda --quiet
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda create --name TEST python=$PY --file requirements-dev.txt --quiet
    source activate TEST
    # Install after to ensure it will be downgraded when testing an older version.
    conda install numpy=$NUMPY
    conda info --all

# Test source distribution.
install:
  - python setup.py check
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist && pip install --no-deps --force-reinstall gsw-${version}.tar.gz && popd

script:
  - if [[ $TEST_TARGET == "default" ]]; then
      pushd gsw && pytest -s -rxs -v tests && popd ;
    fi

  - |
    if [[ $TRAVIS_JOB_NAME == 'deploy' ]]; then
      set -e
      pushd docs
      make clean html linkcheck
      popd
      if [[ -z "$TRAVIS_TAG" ]]; then 
        python -m doctr deploy --build-tags --key-path github_deploy_key.enc --built-docs docs/_build/html dev
      else
        python -m doctr deploy --build-tags --key-path github_deploy_key.enc --built-docs docs/_build/html "version-$TRAVIS_TAG"
        python -m doctr deploy --build-tags --key-path github_deploy_key.enc --built-docs docs/_build/html .
      fi
    fi


deploy:
  skip_cleanup: true
  provider: pypi
  user: ocefpaf
  password:
    secure: aC6ZixeGhCmxdn3a4skQJHIK9Ffj/p5O1cOjHKXZh1vhHy1t5oEfk1HayWdLq2wRwODx9+Ern6ZsWRv+jiSPiqlHgOL74SHT+ByAX/WaylhhySS5JeTN+jT0vOoB7IZRtAb1QVA7mIifbrLTyHw+jX5pUt+ue1LI5zg+M9ny3E0gFYut6t3C2zbTCACmk3S5+3DXn4BT5aXJhbnF2NKTNvEzhXuL0Vu08N8pClTIQM8ZR2fniqVcM8oCPL/Ecouf7Z6L5ofl8cqdloe9e50/01XCKQs0EUWVko8XlBiKvjOUoUn3oB1rif8hahQpHIrDWNShvBqp1LE/Sxmv2FmtC0C+WAqivMqWyLOxrtZnDpk0/0DGObQ652Ypr2WocC1E2wub7rf1KinNcWmgQGIPzQbUERUYcc2yW1pRfT2oos0QLTzWgTTGlImAeuNo1s9ds7dSYcQCL6z+M0Nq3nZ71gmir22hx/j1N0OQzLBMgxz3m6+pZz6nrNT0YQTFqs/y2A6R8yf46+vySGbzoMKS0OmTmFN6Fr0URoF0oHmztb6y+aVLvHPdtfLV/ryR7DsLKXn7j1FfHoEJNoojCecgL0EZDqWiSX6wLwdTnEkZK56ZTAJGjKPFTPtfxaNLdmc+kweGhIXINp4qacWASIYBm1vldToSC2KiRo+aPKcYRaQ=
  distributions: sdist
  upload_docs: no
  on:
    repo: TEOS-10/GSW-Python
    tags: true
    all_branches: master
    condition: '$TRAVIS_JOB_NAME == "deploy"'
